Add Line Platform Support
NextDotID/proof_server pull request #56
Opened 2023-01-16 14:34 UTC by ars0x

Channel access token
https://developers.line.biz/en/docs/messaging-api/channel-access-tokens/
Line bot
https://developers.line.biz/en/docs/messaging-api/building-bot/
Without line bot,we can't use messaging api.

2023-01-17 07:02 UTC, nykma commented
I'm not familiar with Line, can other user views whole messages (aka proof posts) in this Line channel?

2023-01-17 09:03 UTC, ars0x commented
Yes,Line users can use two types of Line accounts,line account and line official account.The messaging api only supports Line official accounts,But Line official accounts can interact with users in line group chats or multi-person chats using the messaging api.
Kindly check,
https://developers.line.biz/en/docs/messaging-api/group-chats/

2023-01-29 15:39 UTC, ars0x commented
Please take now that

2023-01-30 09:07 UTC, nykma requested changes
Using a `telegram` SDK to deal with `line` platform?

Not even wrong.

2023-01-30 09:07 UTC, nykma commented on validator/line/line.go
> +    "github.com/gotd/td/line"
`go: module github.com/gotd/td@upgrade found (v0.75.0), but does not contain package github.com/gotd/td/line`

2023-01-30 09:07 UTC, nykma commented on validator/line/line.go
> +    "github.com/gotd/td/ln"
`go: module github.com/gotd/td@upgrade found (v0.75.0), but does not contain package github.com/gotd/td/ln`

2023-01-30 12:16 UTC, ars0x commented
Please check now

2023-01-30 12:21 UTC, closed without merging